name: mgen_cli
description: A sample command-line application.
version: 1.0.0
repository: https://github.com/Yoeri-z/mgen_cli
executables:
  mgen: model_generator
environment:
  sdk: ^3.0.3

dependencies:
  yaml: ^3.1.2


dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
