name: mgen_cli
description: An easy to use commandline tool to make serilization easier
version: 1.1.2
repository: https://github.com/Yoeri-z/mgen_cli
executables:
  mgen: mgen_cli
environment:
  sdk: ^3.0.3

dependencies:
  code_builder: ^4.6.0
  yaml: ^3.1.2


dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
