const modelAbstractTemplate = '''
/// THIS IS AN AUTOGENERATED SCRIPT DO NOT MODIFY

abstract class Model<T> {
  ///converts an object into a map with a json like structure
  Map<String, dynamic> toJson();

  T copyWith();
}''';
